services:
  app:
    ports:
      - '18080:80'
    restart: unless-stopped

  database:
    restart: unless-stopped
    ports:
      - '43306:3306'
    volumes:
      - mariadb_data:/var/lib/mysql

  frontend:
    build:
      context: .
      target: frontend
    ports:
      - '12466:3000'
    environment:
      PUBLIC_API_BASE_URL: https://api.hs-debaiter.negge.fi

volumes:
  mariadb_data:
